name: Node CI

on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [macos-latest, windows-latest, ubuntu-18.04]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run npm audit
        run: npm audit

      - name: Run npm audit fix
        run: npm audit fix


      - name: npm install, build and test
        run: |
          npm install
          npm run build --if-present
          npm test
        env:
          CI: true

      - name: Upload webpack artifacts
        uses: actions/upload-artifact@v2
        with:
          name: webpack-artifacts
          path: public/
