name: Node CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v1
        with:
          node-version: 18.17.1


      - name: npm install, build and test
        run: |
          npm i
          npm run build --if-present
          chmod +x ./node_modules/.bin/ts-mocha
          chmod +x ./node_modules/.bin/c8
         # npm run test:coverage
        env:
          CI: true

      - name: Upload coverage as artifact
        uses: actions/upload-artifact@main
        with:
          name: coverage
          path: coverage/tmp
